[build]
  command = "python3 research/import-imdb-tv.py && python3 research/enrich-imdb-duration.py && python3 research/enrich-imdb-filters.py"
  publish = "."

[[headers]]
  for = "/data/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
