#!/usr/bin/env python3
"""Enrich Morningstar's generated IMDb TV archive with total series duration.

The base archive is generated by import-imdb-tv.py from IMDb's official
non-commercial title basics/ratings datasets. This pass adds episode-derived
runtime data using title.episode.tsv.gz plus title.basics.tsv.gz.

A total runtime is marked exact only when every IMDb-listed episode for the
series has a known runtime. Partial/unknown totals stay null so the default
"under 4 hours" filter never guesses.
"""

from __future__ import annotations

import csv
import gzip
import hashlib
import json
import shutil
import tempfile
import urllib.request
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "data" / "imdb"
MANIFEST_PATH = OUT_DIR / "manifest.json"
REPORT_PATH = ROOT / "research" / "imdb-tv-import-report.json"
BASICS_URL = "https://datasets.imdbws.com/title.basics.tsv.gz"
EPISODE_URL = "https://datasets.imdbws.com/title.episode.tsv.gz"
USER_AGENT = "Morningstar personal IMDb archive duration enricher/1.0"
APPENDED_FIELDS = [
    "totalRuntimeMinutes",
    "episodeCount",
    "knownEpisodeRuntimeCount",
    "knownEpisodeRuntimeMinutes",
]


def download(url: str, destination: Path) -> None:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=120) as response, destination.open("wb") as output:
        shutil.copyfileobj(response, output, length=1024 * 1024)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def imdb_number(tconst: str) -> int:
    if not tconst.startswith("tt"):
        raise RuntimeError(f"Unexpected IMDb title id: {tconst!r}")
    return int(tconst[2:])


def nullable_int(value: str) -> int | None:
    if not value or value == r"\N":
        return None
    try:
        return int(value)
    except ValueError:
        return None


def write_json(path: Path, payload: object, *, pretty: bool = False) -> None:
    if pretty:
        text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    else:
        text = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    path.write_text(text, encoding="utf-8")


def load_archive(manifest: dict[str, object]) -> tuple[list[list[object]], set[str]]:
    records: list[list[object]] = []
    series_ids: set[str] = set()
    for entry in manifest["files"]:
        path = OUT_DIR / entry["file"]
        chunk = json.loads(path.read_text(encoding="utf-8"))
        records.extend(chunk)
        series_ids.update(str(record[0]) for record in chunk)
    if len(records) != manifest["totalTitles"]:
        raise RuntimeError("IMDb archive record count does not match manifest before duration enrichment")
    return records, series_ids


def iter_target_episodes(path: Path, series_ids: set[str]):
    previous = -1
    with gzip.open(path, "rt", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        for row in reader:
            parent = row["parentTconst"]
            if parent not in series_ids:
                continue
            number = imdb_number(row["tconst"])
            if number < previous:
                raise RuntimeError("title.episode.tsv.gz is not ordered by tconst as expected")
            previous = number
            yield number, row["tconst"], parent


def iter_basics_runtimes(path: Path):
    previous = -1
    with gzip.open(path, "rt", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        for row in reader:
            number = imdb_number(row["tconst"])
            if number < previous:
                raise RuntimeError("title.basics.tsv.gz is not ordered by tconst as expected")
            previous = number
            yield number, row["tconst"], nullable_int(row["runtimeMinutes"])


def main() -> None:
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    if manifest.get("durationEnrichment"):
        print("IMDb duration enrichment already present; rebuilding it from the fresh archive anyway.")

    records, series_ids = load_archive(manifest)
    episode_count: Counter[str] = Counter()
    known_count: Counter[str] = Counter()
    known_minutes: Counter[str] = Counter()

    with tempfile.TemporaryDirectory(prefix="morningstar-imdb-duration-") as temp_dir_name:
        temp_dir = Path(temp_dir_name)
        basics_path = temp_dir / "title.basics.tsv.gz"
        episode_path = temp_dir / "title.episode.tsv.gz"
        download(BASICS_URL, basics_path)
        download(EPISODE_URL, episode_path)

        basics_iter = iter_basics_runtimes(basics_path)
        basics_current = next(basics_iter, None)

        for episode_number, _episode_id, parent in iter_target_episodes(episode_path, series_ids):
            episode_count[parent] += 1
            while basics_current is not None and basics_current[0] < episode_number:
                basics_current = next(basics_iter, None)
            if basics_current is not None and basics_current[0] == episode_number:
                runtime = basics_current[2]
                if runtime is not None and runtime > 0:
                    known_count[parent] += 1
                    known_minutes[parent] += runtime

        exact = partial = unknown = under_four = 0
        id_to_duration: dict[str, tuple[int | None, int, int, int]] = {}
        for tconst in series_ids:
            episodes = episode_count[tconst]
            known = known_count[tconst]
            minutes = known_minutes[tconst]
            total = minutes if episodes > 0 and known == episodes else None
            if total is not None:
                exact += 1
                under_four += int(total < 240)
            elif known > 0:
                partial += 1
            else:
                unknown += 1
            id_to_duration[tconst] = (total, episodes, known, minutes)

        for record in records:
            if len(record) > 11:
                del record[11:]
            record.extend(id_to_duration[str(record[0])])

        cursor = 0
        new_files = []
        for entry in manifest["files"]:
            count = int(entry["count"])
            chunk = records[cursor : cursor + count]
            cursor += count
            path = OUT_DIR / entry["file"]
            write_json(path, chunk)
            new_entry = dict(entry)
            new_entry["bytes"] = path.stat().st_size
            new_entry["sha256"] = sha256_file(path)
            new_files.append(new_entry)
        if cursor != len(records):
            raise RuntimeError("Duration rewrite did not consume all IMDb records")

        fields = list(manifest.get("fields") or [])
        fields = fields[:11] + APPENDED_FIELDS
        manifest["schemaVersion"] = 2
        manifest["generatedAt"] = datetime.now(timezone.utc).isoformat()
        manifest["fields"] = fields
        manifest["files"] = new_files
        source = dict(manifest.get("source") or {})
        source["episodeUrl"] = EPISODE_URL
        source["durationBasicsUrl"] = BASICS_URL
        source["durationBasicsSha256"] = sha256_file(basics_path)
        source["episodeSha256"] = sha256_file(episode_path)
        manifest["source"] = source
        manifest["durationEnrichment"] = {
            "method": "Sum runtimeMinutes for every IMDb-listed episode. Exact only when every listed episode has a known runtime.",
            "exactTitles": exact,
            "partialTitles": partial,
            "unknownTitles": unknown,
            "exactUnder4Hours": under_four,
            "defaultMaxHoursExclusive": 4,
            "includeUnknownByDefault": False,
        }
        defaults = dict(manifest.get("uiDefaults") or {})
        defaults["maxTotalHoursExclusive"] = 4
        defaults["includeUnknownDuration"] = False
        manifest["uiDefaults"] = defaults
        write_json(MANIFEST_PATH, manifest, pretty=True)

        report = json.loads(REPORT_PATH.read_text(encoding="utf-8")) if REPORT_PATH.exists() else {}
        report["durationEnrichment"] = manifest["durationEnrichment"] | {
            "source": {
                "episodeUrl": EPISODE_URL,
                "basicsUrl": BASICS_URL,
            },
            "unknownHandling": "Unknown/partial total durations are excluded by the default <4h filter. The UI offers an explicit include option and a web-search link per unknown title.",
        }
        write_json(REPORT_PATH, report, pretty=True)

    print(
        f"IMDb durations enriched: {exact:,} exact, {partial:,} partial, {unknown:,} unknown; "
        f"{under_four:,} exact titles under 4 hours."
    )


if __name__ == "__main__":
    main()
